// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.2.0
// Project name: AirQualityMonitor

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_TVOC_Panel_1 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_TVOC_Panel_1, 14);
lv_obj_set_height( ui_TVOC_Panel_1, 20);
lv_obj_set_x( ui_TVOC_Panel_1, 40 );
lv_obj_set_y( ui_TVOC_Panel_1, 45 );
lv_obj_set_align( ui_TVOC_Panel_1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_TVOC_Panel_1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_TVOC_Panel_1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TVOC_Panel_1, lv_color_hex(0x89E0FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TVOC_Panel_1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_main_stop(ui_TVOC_Panel_1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_TVOC_Panel_1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_TVOC_Panel_1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_TVOC_Panel_1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_TVOC_Panel_1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_TVOC_Panel_1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_TVOC_Panel_1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_TVOC_Panel_1, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_TVOC_Panel_1, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_TVOC_Panel_1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_TVOC_Panel_1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_TVOC_Panel_1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_TVOC_Panel_1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_TVOC_Panel_1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_TVOC_Panel_1, 4, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TVOC_Panel_1, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TVOC_Panel_1, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_main_stop(ui_TVOC_Panel_1, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_TVOC_Panel_1, 255, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_TVOC_Panel_2 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_TVOC_Panel_2, 14);
lv_obj_set_height( ui_TVOC_Panel_2, 20);
lv_obj_set_x( ui_TVOC_Panel_2, 40 );
lv_obj_set_y( ui_TVOC_Panel_2, 25 );
lv_obj_set_align( ui_TVOC_Panel_2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_TVOC_Panel_2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_TVOC_Panel_2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TVOC_Panel_2, lv_color_hex(0x90EE90), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TVOC_Panel_2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_main_stop(ui_TVOC_Panel_2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_TVOC_Panel_2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_TVOC_Panel_2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_TVOC_Panel_2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_TVOC_Panel_2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_TVOC_Panel_2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_TVOC_Panel_2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_TVOC_Panel_2, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_TVOC_Panel_2, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_TVOC_Panel_2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_TVOC_Panel_2, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_TVOC_Panel_2, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_TVOC_Panel_2, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_TVOC_Panel_2, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_TVOC_Panel_2, 4, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TVOC_Panel_2, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TVOC_Panel_2, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_main_stop(ui_TVOC_Panel_2, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_TVOC_Panel_2, 255, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_TVOC_Panel_3 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_TVOC_Panel_3, 14);
lv_obj_set_height( ui_TVOC_Panel_3, 20);
lv_obj_set_x( ui_TVOC_Panel_3, 40 );
lv_obj_set_y( ui_TVOC_Panel_3, 5 );
lv_obj_set_align( ui_TVOC_Panel_3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_TVOC_Panel_3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_TVOC_Panel_3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TVOC_Panel_3, lv_color_hex(0xFFD700), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TVOC_Panel_3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_main_stop(ui_TVOC_Panel_3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_TVOC_Panel_3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_TVOC_Panel_3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_TVOC_Panel_3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_TVOC_Panel_3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_TVOC_Panel_3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_TVOC_Panel_3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_TVOC_Panel_3, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_TVOC_Panel_3, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_TVOC_Panel_3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_TVOC_Panel_3, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_TVOC_Panel_3, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_TVOC_Panel_3, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_TVOC_Panel_3, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_TVOC_Panel_3, 4, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TVOC_Panel_3, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TVOC_Panel_3, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_main_stop(ui_TVOC_Panel_3, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_TVOC_Panel_3, 255, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_TVOC_Panel_4 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_TVOC_Panel_4, 14);
lv_obj_set_height( ui_TVOC_Panel_4, 20);
lv_obj_set_x( ui_TVOC_Panel_4, 40 );
lv_obj_set_y( ui_TVOC_Panel_4, -15 );
lv_obj_set_align( ui_TVOC_Panel_4, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_TVOC_Panel_4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_TVOC_Panel_4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TVOC_Panel_4, lv_color_hex(0xFFA500), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TVOC_Panel_4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_main_stop(ui_TVOC_Panel_4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_TVOC_Panel_4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_TVOC_Panel_4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_TVOC_Panel_4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_TVOC_Panel_4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_TVOC_Panel_4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_TVOC_Panel_4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_TVOC_Panel_4, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_TVOC_Panel_4, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_TVOC_Panel_4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_TVOC_Panel_4, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_TVOC_Panel_4, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_TVOC_Panel_4, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_TVOC_Panel_4, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_TVOC_Panel_4, 4, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TVOC_Panel_4, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TVOC_Panel_4, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_main_stop(ui_TVOC_Panel_4, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_TVOC_Panel_4, 255, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_TVOC_Panel_5 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_TVOC_Panel_5, 14);
lv_obj_set_height( ui_TVOC_Panel_5, 20);
lv_obj_set_x( ui_TVOC_Panel_5, 40 );
lv_obj_set_y( ui_TVOC_Panel_5, -35 );
lv_obj_set_align( ui_TVOC_Panel_5, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_TVOC_Panel_5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_TVOC_Panel_5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TVOC_Panel_5, lv_color_hex(0xFF5050), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TVOC_Panel_5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_main_stop(ui_TVOC_Panel_5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_TVOC_Panel_5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_TVOC_Panel_5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_TVOC_Panel_5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_TVOC_Panel_5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_TVOC_Panel_5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_TVOC_Panel_5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_TVOC_Panel_5, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_TVOC_Panel_5, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_TVOC_Panel_5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_TVOC_Panel_5, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_TVOC_Panel_5, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_TVOC_Panel_5, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_TVOC_Panel_5, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_TVOC_Panel_5, 4, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TVOC_Panel_5, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TVOC_Panel_5, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_main_stop(ui_TVOC_Panel_5, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_TVOC_Panel_5, 255, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_Arrow_AQI = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Arrow_AQI, &ui_img_1628699646);
lv_obj_set_width( ui_Arrow_AQI, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Arrow_AQI, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Arrow_AQI, 24 );
lv_obj_set_y( ui_Arrow_AQI, 45 );
lv_obj_set_align( ui_Arrow_AQI, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Arrow_AQI, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Arrow_AQI, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Arrow_eC02 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Arrow_eC02, &ui_img_764893558);
lv_obj_set_width( ui_Arrow_eC02, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Arrow_eC02, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Arrow_eC02, -24 );
lv_obj_set_y( ui_Arrow_eC02, 45 );
lv_obj_set_align( ui_Arrow_eC02, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Arrow_eC02, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Arrow_eC02, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_AQI_Value = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_AQI_Value, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AQI_Value, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_AQI_Value, 74 );
lv_obj_set_y( ui_AQI_Value, 59 );
lv_obj_set_align( ui_AQI_Value, LV_ALIGN_CENTER );
lv_label_set_text(ui_AQI_Value,"0");
lv_obj_set_style_text_font(ui_AQI_Value, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_eCO2_Value = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_eCO2_Value, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_eCO2_Value, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_eCO2_Value, -61 );
lv_obj_set_y( ui_eCO2_Value, 59 );
lv_obj_set_align( ui_eCO2_Value, LV_ALIGN_CENTER );
lv_label_set_text(ui_eCO2_Value,"00000");
lv_obj_set_style_text_font(ui_eCO2_Value, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AQI_Panel_1 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_AQI_Panel_1, 14);
lv_obj_set_height( ui_AQI_Panel_1, 20);
lv_obj_set_x( ui_AQI_Panel_1, -40 );
lv_obj_set_y( ui_AQI_Panel_1, 45 );
lv_obj_set_align( ui_AQI_Panel_1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_AQI_Panel_1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_AQI_Panel_1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_AQI_Panel_1, lv_color_hex(0x89E0FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_AQI_Panel_1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_main_stop(ui_AQI_Panel_1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_AQI_Panel_1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_AQI_Panel_1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_AQI_Panel_1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_AQI_Panel_1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_AQI_Panel_1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_AQI_Panel_1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_AQI_Panel_1, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_AQI_Panel_1, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_AQI_Panel_1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_AQI_Panel_1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_AQI_Panel_1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_AQI_Panel_1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_AQI_Panel_1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_AQI_Panel_1, 4, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_AQI_Panel_1, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_AQI_Panel_1, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_main_stop(ui_AQI_Panel_1, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_AQI_Panel_1, 255, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_AQI_Panel_2 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_AQI_Panel_2, 14);
lv_obj_set_height( ui_AQI_Panel_2, 20);
lv_obj_set_x( ui_AQI_Panel_2, -40 );
lv_obj_set_y( ui_AQI_Panel_2, 25 );
lv_obj_set_align( ui_AQI_Panel_2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_AQI_Panel_2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_AQI_Panel_2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_AQI_Panel_2, lv_color_hex(0x90EE90), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_AQI_Panel_2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_main_stop(ui_AQI_Panel_2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_AQI_Panel_2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_AQI_Panel_2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_AQI_Panel_2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_AQI_Panel_2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_AQI_Panel_2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_AQI_Panel_2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_AQI_Panel_2, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_AQI_Panel_2, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_AQI_Panel_2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_AQI_Panel_2, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_AQI_Panel_2, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_AQI_Panel_2, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_AQI_Panel_2, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_AQI_Panel_2, 4, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_AQI_Panel_2, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_AQI_Panel_2, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_main_stop(ui_AQI_Panel_2, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_AQI_Panel_2, 255, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_AQI_Panel_3 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_AQI_Panel_3, 14);
lv_obj_set_height( ui_AQI_Panel_3, 20);
lv_obj_set_x( ui_AQI_Panel_3, -40 );
lv_obj_set_y( ui_AQI_Panel_3, 5 );
lv_obj_set_align( ui_AQI_Panel_3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_AQI_Panel_3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_AQI_Panel_3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_AQI_Panel_3, lv_color_hex(0xFFD700), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_AQI_Panel_3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_main_stop(ui_AQI_Panel_3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_AQI_Panel_3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_AQI_Panel_3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_AQI_Panel_3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_AQI_Panel_3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_AQI_Panel_3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_AQI_Panel_3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_AQI_Panel_3, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_AQI_Panel_3, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_AQI_Panel_3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_AQI_Panel_3, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_AQI_Panel_3, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_AQI_Panel_3, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_AQI_Panel_3, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_AQI_Panel_3, 4, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_AQI_Panel_3, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_AQI_Panel_3, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_main_stop(ui_AQI_Panel_3, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_AQI_Panel_3, 255, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_AQI_Panel_4 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_AQI_Panel_4, 14);
lv_obj_set_height( ui_AQI_Panel_4, 20);
lv_obj_set_x( ui_AQI_Panel_4, -40 );
lv_obj_set_y( ui_AQI_Panel_4, -15 );
lv_obj_set_align( ui_AQI_Panel_4, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_AQI_Panel_4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_AQI_Panel_4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_AQI_Panel_4, lv_color_hex(0xFFA500), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_AQI_Panel_4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_main_stop(ui_AQI_Panel_4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_AQI_Panel_4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_AQI_Panel_4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_AQI_Panel_4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_AQI_Panel_4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_AQI_Panel_4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_AQI_Panel_4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_AQI_Panel_4, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_AQI_Panel_4, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_AQI_Panel_4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_AQI_Panel_4, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_AQI_Panel_4, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_AQI_Panel_4, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_AQI_Panel_4, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_AQI_Panel_4, 4, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_AQI_Panel_4, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_AQI_Panel_4, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_main_stop(ui_AQI_Panel_4, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_AQI_Panel_4, 255, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_AQI_Panel_5 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_AQI_Panel_5, 14);
lv_obj_set_height( ui_AQI_Panel_5, 20);
lv_obj_set_x( ui_AQI_Panel_5, -40 );
lv_obj_set_y( ui_AQI_Panel_5, -35 );
lv_obj_set_align( ui_AQI_Panel_5, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_AQI_Panel_5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_AQI_Panel_5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_AQI_Panel_5, lv_color_hex(0xFF5050), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_AQI_Panel_5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_main_stop(ui_AQI_Panel_5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_AQI_Panel_5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_AQI_Panel_5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_AQI_Panel_5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_AQI_Panel_5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_AQI_Panel_5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_AQI_Panel_5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_AQI_Panel_5, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_AQI_Panel_5, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_AQI_Panel_5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_AQI_Panel_5, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_AQI_Panel_5, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_AQI_Panel_5, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_AQI_Panel_5, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_AQI_Panel_5, 4, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_AQI_Panel_5, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_AQI_Panel_5, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_main_stop(ui_AQI_Panel_5, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_AQI_Panel_5, 255, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_eCO2 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_eCO2, &ui_img_1740126349);
lv_obj_set_width( ui_eCO2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_eCO2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_eCO2, -67 );
lv_obj_set_y( ui_eCO2, 0 );
lv_obj_set_align( ui_eCO2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_eCO2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_eCO2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_AQI = lv_img_create(ui_Screen1);
lv_img_set_src(ui_AQI, &ui_img_2097537603);
lv_obj_set_width( ui_AQI, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AQI, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_AQI, 67 );
lv_obj_set_y( ui_AQI, 0 );
lv_obj_set_align( ui_AQI, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_AQI, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_AQI, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

}
