// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.2.0
// Project name: AirQualityMonitor


#ifndef _AIRQUALITYMONITOR_UI_H
#define _AIRQUALITYMONITOR_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_TVOC_Panel_1;
extern lv_obj_t *ui_TVOC_Panel_2;
extern lv_obj_t *ui_TVOC_Panel_3;
extern lv_obj_t *ui_TVOC_Panel_4;
extern lv_obj_t *ui_TVOC_Panel_5;
extern lv_obj_t *ui_Arrow_AQI;
extern lv_obj_t *ui_Arrow_eC02;
extern lv_obj_t *ui_AQI_Value;
extern lv_obj_t *ui_eCO2_Value;
extern lv_obj_t *ui_AQI_Panel_1;
extern lv_obj_t *ui_AQI_Panel_2;
extern lv_obj_t *ui_AQI_Panel_3;
extern lv_obj_t *ui_AQI_Panel_4;
extern lv_obj_t *ui_AQI_Panel_5;
extern lv_obj_t *ui_eCO2;
extern lv_obj_t *ui_AQI;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE(ui_img_1628699646);   // assets\triangle-custom.png
LV_IMG_DECLARE(ui_img_764893558);   // assets\triangle-custom2.png
LV_IMG_DECLARE(ui_img_1740126349);   // assets\molecule-co2-custom.png
LV_IMG_DECLARE(ui_img_2097537603);   // assets\air-filter-custom.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
